language: objective-c
osx_image: xcode10.1
xcode_project: Framework/YYCache.xcodeproj
xcode_scheme: YYCache

before_install:
  - env
  - xcodebuild -version
  - xcodebuild -showsdks
  - xcpretty --version

script:
  - set -o pipefail
  - xcodebuild clean build -project "$TRAVIS_XCODE_PROJECT"  -scheme "$TRAVIS_XCODE_SCHEME" | xcpretty
  - echo "git \"file://$(pwd)\" \"${TRAVIS_PULL_REQUEST_BRANCH}\"" > Cartfile
  - carthage update --platform tvos
  - carthage update --platform ios

